### ISSUE TITLE
gradle problem

### ISSUE THREAD

**Issue by pjebs** [apl-devs/Permissions-Helper#9]
I added this to gradle:

`compile 'com.amqtech:perms-helper:1.1'`

Gradle complains saying that `Failed to resolve: com.android.support.constraint:constraint-layout:1.0.0-alpha1`

What am i doing wrong. I noticed that you have made numerous changes.

**Comment by Andrew-Quebe** [comment]
I'm working on releasing 1.1 to maven...just give me a bit. Please do not open anymore issues. I will update you on your last issue.

The issue is that the maven repo (`com.amqtech`) is no longer in use. It's an old domain name. I am trying to create `com.github.apl-devs` instead. Just bear with me...been working on this for hours today.

**Comment by Andrew-Quebe** [comment]
@pjebs Follow the instructions here: https://github.com/apl-devs/Permissions-Helper/releases/tag/v1.1

The readme has also been updated.

**Comment by pjebs** [comment]
thank you @Andrew-Quebe for your hard work.
